-- The whole schema, in one file.
--
-- There is one migration because there has only ever been one shape worth
-- describing: this one. A chain that creates a table and then drops it two
-- files later is a history lesson every clone has to sit through, and reading
-- it is not how anybody learns what the database looks like -- db/schema.ts is.
-- The next migration in this folder will be a real change to what is below.
--
-- Everything except `log_entries` is generated by drizzle-kit from
-- db/schema.ts. `log_entries` is hand-written, because `PARTITION BY RANGE` has
-- no Drizzle expression and the partition management below is a thing this
-- system DOES rather than a shape it has.

CREATE TYPE "public"."member_role" AS ENUM('admin', 'read');--> statement-breakpoint
CREATE TYPE "public"."source_kind" AS ENUM('web', 'desktop', 'mobile', 'server', 'other');--> statement-breakpoint
CREATE TABLE "dashboards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"name" text DEFAULT 'Overview' NOT NULL,
	"slug" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"layout" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- One partitioned table, one row shape, for all telemetry. An error is a log
-- entry, an event is a log entry, a metric sample is a log entry. Meaning is
-- assigned by CONVENTION at write time and by QUERY at read time, never by a
-- closed set of types in the backend.
--
-- Five columns are promoted -- project_id, time, distinct_id, severity, name --
-- plus the two the table needs to work at all: entry_id for dedup, ingested_at
-- for debugging. Everything else lives in `attributes`, reached by path, using
-- the OpenTelemetry semantic-convention keys where OTel has named the thing and
-- `firstrun.*` where it has not.
--
-- There is no `surface` column and no enum for one. A surface is a property of
-- the SOURCE, so it arrives as the `firstrun.source.surface` attribute the edge
-- stamps from the source row. An enum on the entry would be a sixth promoted
-- column pretending to be a type.
--
-- No foreign key to `projects` either. A partitioned table can carry one, but
-- then every partition carries the trigger, and `deleteProject` in db/repo.ts
-- already removes a project's entries explicitly. The cascade was doing work
-- the repo does anyway, on the largest table in the database.
--
-- The primary key is (project_id, time, entry_id), and `time` is in it because
-- it has to be: Postgres will not enforce a unique constraint on a partitioned
-- table unless the constraint contains the partition key. Dedup wants
-- (project_id, entry_id) alone -- every SDK replays its disk queue after a
-- crash, so the same entry id arriving twice is the normal case that
-- ON CONFLICT DO NOTHING absorbs -- and a replayed entry carries the timestamp
-- it was stamped with on the client, so the same id genuinely does arrive with
-- the same time.
--
-- `time` sits SECOND rather than last so this key's btree is also the
-- per-project time-range index every query starts with. That is one fewer btree
-- on the hottest table in the database.
--
-- The constraint is named the way drizzle names it, which is what
-- meta/0000_snapshot.json records. Nothing references it by name
-- (db/log-entries.ts deliberately writes a bare `ON CONFLICT DO NOTHING` so
-- that the schema owns which columns dedup uses), but a database whose
-- catalogue disagrees with the snapshot is a diff waiting to appear in
-- somebody's next `generate`.
CREATE TABLE "log_entries" (
	"project_id" uuid NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"entry_id" uuid NOT NULL,
	"ingested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"distinct_id" text NOT NULL,
	"severity" smallint,
	"name" text NOT NULL,
	"attributes" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "log_entries_project_id_time_entry_id_pk" PRIMARY KEY("project_id","time","entry_id")
) PARTITION BY RANGE ("time");
--> statement-breakpoint
-- The safety net. An entry stamped in 2019 by a machine with a wrong clock, or
-- one that arrives the second before the next month's partition is created,
-- lands here instead of failing the insert. Ingest must never reject a row for
-- an administrative reason.
--
-- It is a net, not a home: `log_entries_create_partition` moves rows out of it
-- into the real partition when that month is created, because a default
-- partition holding rows for a range you later want to add is the one thing
-- that makes adding it fail.
CREATE TABLE "log_entries_default" PARTITION OF "log_entries" DEFAULT;
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"logo" "bytea",
	"logo_mime_type" text,
	"logo_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"name" text NOT NULL,
	"kind" "source_kind" NOT NULL,
	"asset_name" text,
	"ingest_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"github_id" bigint NOT NULL,
	"login" text NOT NULL,
	"name" text,
	"email" text,
	"avatar_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace_members" (
	"workspace_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "member_role" DEFAULT 'read' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workspace_members_workspace_id_user_id_pk" PRIMARY KEY("workspace_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "workspaces" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"logo" "bytea",
	"logo_mime_type" text,
	"logo_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sources" ADD CONSTRAINT "sources_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "dashboards_project_slug_key" ON "dashboards" USING btree ("project_id","slug");--> statement-breakpoint
CREATE INDEX "dashboards_project_idx" ON "dashboards" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "log_entries_name_time_idx" ON "log_entries" USING btree ("project_id","name","time");--> statement-breakpoint
CREATE INDEX "log_entries_severity_time_idx" ON "log_entries" USING btree ("project_id","severity","time");--> statement-breakpoint
CREATE INDEX "log_entries_distinct_time_idx" ON "log_entries" USING btree ("project_id","distinct_id","time");--> statement-breakpoint
CREATE INDEX "log_entries_attributes_idx" ON "log_entries" USING gin ("attributes");--> statement-breakpoint
CREATE UNIQUE INDEX "projects_workspace_slug_key" ON "projects" USING btree ("workspace_id","slug");--> statement-breakpoint
CREATE INDEX "projects_workspace_idx" ON "projects" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "sessions_user_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_expiry_idx" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "sources_ingest_key_key" ON "sources" USING btree ("ingest_key");--> statement-breakpoint
CREATE INDEX "sources_project_idx" ON "sources" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_github_id_key" ON "users" USING btree ("github_id");--> statement-breakpoint
CREATE INDEX "members_user_idx" ON "workspace_members" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "workspaces_slug_key" ON "workspaces" USING btree ("slug");--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Partition management
-- ---------------------------------------------------------------------------

-- MONTHLY, not weekly.
--
-- Partition count is a real cost: pruning happens at plan time and the planner
-- walks the list, so a dashboard running twenty compiled queries pays it twenty
-- times. Monthly keeps a year of history at thirteen partitions; weekly would
-- make it fifty-three for finer drop granularity nobody has asked for. The
-- windows the product actually offers -- 7, 14, 30, 90, 365 days -- prune to
-- between one and thirteen partitions either way, and retention sold in months
-- is retention people can reason about.
--
-- Weekly is the right answer at a volume where one month of one project does
-- not fit comfortably in cache. Changing granularity later means creating the
-- new partitions and copying, not redesigning, because nothing above this file
-- knows how wide a partition is.

CREATE OR REPLACE FUNCTION log_entries_partition_name(bound date)
  RETURNS text LANGUAGE sql IMMUTABLE AS
$$ SELECT 'log_entries_' || to_char($1, 'YYYY_MM') $$;--> statement-breakpoint

-- Creates the partition covering the month `month_start` falls in, and returns
-- its name. Idempotent: an existing partition is returned untouched.
--
-- The dance with the default partition is the whole reason this is a function
-- and not a CREATE TABLE. Attaching a partition while the default holds rows in
-- the new range fails, so the rows are moved first: build the table standalone,
-- drain the matching rows out of the default into it, give it a CHECK matching
-- the bound so ATTACH can skip the validation scan, attach, drop the now
-- redundant CHECK.
CREATE OR REPLACE FUNCTION log_entries_create_partition(month_start date)
  RETURNS text LANGUAGE plpgsql AS
$$
DECLARE
  start_at date := date_trunc('month', month_start)::date;
  end_at   date := (date_trunc('month', month_start) + interval '1 month')::date;
  part     text := log_entries_partition_name(date_trunc('month', month_start)::date);
BEGIN
  IF to_regclass('public.' || quote_ident(part)) IS NOT NULL THEN
    RETURN part;
  END IF;

  EXECUTE format('CREATE TABLE %I (LIKE log_entries INCLUDING DEFAULTS)', part);

  EXECUTE format(
    'WITH moved AS (
       DELETE FROM log_entries_default
        WHERE "time" >= %L AND "time" < %L
        RETURNING *
     )
     INSERT INTO %I SELECT * FROM moved',
    start_at, end_at, part
  );

  EXECUTE format(
    'ALTER TABLE %I ADD CONSTRAINT %I CHECK ("time" >= %L AND "time" < %L)',
    part, part || '_bound', start_at, end_at
  );

  EXECUTE format(
    'ALTER TABLE log_entries ATTACH PARTITION %I FOR VALUES FROM (%L) TO (%L)',
    part, start_at, end_at
  );

  -- The partition bound now says the same thing, and a redundant CHECK is one
  -- more expression the planner evaluates on every insert.
  EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', part, part || '_bound');

  RETURN part;
END
$$;--> statement-breakpoint

-- Everything from `months_back` months ago through `months_ahead` months from
-- now. Called on every boot, so the month after this one always exists before
-- anybody's clock rolls into it, and a database restored from a year-old dump
-- comes back with somewhere to put its own history.
CREATE OR REPLACE FUNCTION log_entries_ensure_partitions(
  months_back  int DEFAULT 1,
  months_ahead int DEFAULT 2
) RETURNS int LANGUAGE plpgsql AS
$$
DECLARE
  m      date;
  made   int := 0;
BEGIN
  FOR m IN
    SELECT generate_series(
             date_trunc('month', now()) - make_interval(months => months_back),
             date_trunc('month', now()) + make_interval(months => months_ahead),
             interval '1 month'
           )::date
  LOOP
    IF to_regclass('public.' || quote_ident(log_entries_partition_name(m))) IS NULL THEN
      made := made + 1;
    END IF;
    PERFORM log_entries_create_partition(m);
  END LOOP;
  RETURN made;
END
$$;--> statement-breakpoint

-- Retention is dropping a partition. It is never a DELETE.
--
-- A bulk DELETE over a hundred million rows writes a hundred million dead
-- tuples, leaves the indexes bloated, and hands the work to autovacuum at the
-- worst possible moment. DROP TABLE is a catalogue change and an unlink.
--
-- Returns the partitions it dropped, so a caller can log what went rather than
-- how many. The default partition is never a candidate: it has no bound to
-- expire, and dropping it would turn an out-of-range insert back into an error.
CREATE OR REPLACE FUNCTION log_entries_drop_expired(retain_months int)
  RETURNS SETOF text LANGUAGE plpgsql AS
$$
DECLARE
  cutoff date := (date_trunc('month', now()) - make_interval(months => retain_months))::date;
  part   text;
BEGIN
  IF retain_months < 1 THEN
    RAISE EXCEPTION 'retain_months must be at least 1, got %', retain_months;
  END IF;

  FOR part IN
    SELECT c.relname
      FROM pg_class c
      JOIN pg_inherits i ON i.inhrelid = c.oid
      JOIN pg_class p ON p.oid = i.inhparent
     WHERE p.relname = 'log_entries'
       AND c.relname <> 'log_entries_default'
       AND c.relname ~ '^log_entries_[0-9]{4}_[0-9]{2}$'
       -- The name carries the bound, so the cutoff is a string comparison on a
       -- format that sorts chronologically. Reading pg_get_expr(relpartbound)
       -- would mean parsing SQL text to learn something the name already says.
       AND to_date(right(c.relname, 7), 'YYYY_MM') < cutoff
     ORDER BY c.relname
  LOOP
    EXECUTE format('DROP TABLE %I', part);
    RETURN NEXT part;
  END LOOP;
END
$$;--> statement-breakpoint

-- Somewhere for the first entries to go. `applyMigrations` calls this again on
-- every boot, which is what keeps the month after this one ahead of the clock.
SELECT log_entries_ensure_partitions(2, 2);
