/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsTopicRouteImport } from './routes/docs.$topic'
import { Route as WWslugRouteImport } from './routes/w.$wslug'
import { Route as WWslugIndexRouteImport } from './routes/w.$wslug.index'
import { Route as WWslugPslugRouteImport } from './routes/w.$wslug.$pslug'
import { Route as WWslugEventsRouteImport } from './routes/w.$wslug.events'
import { Route as WWslugMembersRouteImport } from './routes/w.$wslug.members'
import { Route as WWslugSettingsRouteImport } from './routes/w.$wslug.settings'
import { Route as WWslugSourcesRouteImport } from './routes/w.$wslug.sources'
import { Route as WWslugUsageRouteImport } from './routes/w.$wslug.usage'
import { Route as WWslugPslugIndexRouteImport } from './routes/w.$wslug.$pslug.index'
import { Route as WWslugPslugSettingsRouteImport } from './routes/w.$wslug.$pslug.settings'
import { Route as WWslugPslugSourcesRouteImport } from './routes/w.$wslug.$pslug.sources'
import { Route as WWslugProjectsNewRouteImport } from './routes/w.$wslug.projects.new'
import { Route as WWslugPslugDashboardsDslugRouteImport } from './routes/w.$wslug.$pslug.dashboards.$dslug'
import { Route as WWslugPslugDashboardsNewRouteImport } from './routes/w.$wslug.$pslug.dashboards.new'
import { Route as WWslugPslugSourcesIndexRouteImport } from './routes/w.$wslug.$pslug.sources.index'
import { Route as WWslugPslugSourcesNewRouteImport } from './routes/w.$wslug.$pslug.sources.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => DocsRoute,
} as any)
const WWslugRoute = WWslugRouteImport.update({
  id: '/w/$wslug',
  path: '/w/$wslug',
  getParentRoute: () => rootRouteImport,
} as any)
const WWslugIndexRoute = WWslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPslugRoute = WWslugPslugRouteImport.update({
  id: '/$pslug',
  path: '/$pslug',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugEventsRoute = WWslugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugMembersRoute = WWslugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugSettingsRoute = WWslugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugSourcesRoute = WWslugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugUsageRoute = WWslugUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPslugIndexRoute = WWslugPslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugPslugRoute,
} as any)
const WWslugPslugSettingsRoute = WWslugPslugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWslugPslugRoute,
} as any)
const WWslugPslugSourcesRoute = WWslugPslugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WWslugPslugRoute,
} as any)
const WWslugProjectsNewRoute = WWslugProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPslugDashboardsDslugRoute =
  WWslugPslugDashboardsDslugRouteImport.update({
    id: '/dashboards/$dslug',
    path: '/dashboards/$dslug',
    getParentRoute: () => WWslugPslugRoute,
  } as any)
const WWslugPslugDashboardsNewRoute =
  WWslugPslugDashboardsNewRouteImport.update({
    id: '/dashboards/new',
    path: '/dashboards/new',
    getParentRoute: () => WWslugPslugRoute,
  } as any)
const WWslugPslugSourcesIndexRoute = WWslugPslugSourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugPslugSourcesRoute,
} as any)
const WWslugPslugSourcesNewRoute = WWslugPslugSourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WWslugPslugSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/w/$wslug': typeof WWslugRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/w/$wslug/$pslug': typeof WWslugPslugRouteWithChildren
  '/w/$wslug/events': typeof WWslugEventsRoute
  '/w/$wslug/members': typeof WWslugMembersRoute
  '/w/$wslug/settings': typeof WWslugSettingsRoute
  '/w/$wslug/sources': typeof WWslugSourcesRoute
  '/w/$wslug/usage': typeof WWslugUsageRoute
  '/w/$wslug/': typeof WWslugIndexRoute
  '/w/$wslug/$pslug/settings': typeof WWslugPslugSettingsRoute
  '/w/$wslug/$pslug/sources': typeof WWslugPslugSourcesRouteWithChildren
  '/w/$wslug/projects/new': typeof WWslugProjectsNewRoute
  '/w/$wslug/$pslug/': typeof WWslugPslugIndexRoute
  '/w/$wslug/$pslug/dashboards/$dslug': typeof WWslugPslugDashboardsDslugRoute
  '/w/$wslug/$pslug/dashboards/new': typeof WWslugPslugDashboardsNewRoute
  '/w/$wslug/$pslug/sources/new': typeof WWslugPslugSourcesNewRoute
  '/w/$wslug/$pslug/sources/': typeof WWslugPslugSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/docs': typeof DocsIndexRoute
  '/w/$wslug/events': typeof WWslugEventsRoute
  '/w/$wslug/members': typeof WWslugMembersRoute
  '/w/$wslug/settings': typeof WWslugSettingsRoute
  '/w/$wslug/sources': typeof WWslugSourcesRoute
  '/w/$wslug/usage': typeof WWslugUsageRoute
  '/w/$wslug': typeof WWslugIndexRoute
  '/w/$wslug/$pslug/settings': typeof WWslugPslugSettingsRoute
  '/w/$wslug/projects/new': typeof WWslugProjectsNewRoute
  '/w/$wslug/$pslug': typeof WWslugPslugIndexRoute
  '/w/$wslug/$pslug/dashboards/$dslug': typeof WWslugPslugDashboardsDslugRoute
  '/w/$wslug/$pslug/dashboards/new': typeof WWslugPslugDashboardsNewRoute
  '/w/$wslug/$pslug/sources/new': typeof WWslugPslugSourcesNewRoute
  '/w/$wslug/$pslug/sources': typeof WWslugPslugSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/w/$wslug': typeof WWslugRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/w/$wslug/$pslug': typeof WWslugPslugRouteWithChildren
  '/w/$wslug/events': typeof WWslugEventsRoute
  '/w/$wslug/members': typeof WWslugMembersRoute
  '/w/$wslug/settings': typeof WWslugSettingsRoute
  '/w/$wslug/sources': typeof WWslugSourcesRoute
  '/w/$wslug/usage': typeof WWslugUsageRoute
  '/w/$wslug/': typeof WWslugIndexRoute
  '/w/$wslug/$pslug/settings': typeof WWslugPslugSettingsRoute
  '/w/$wslug/$pslug/sources': typeof WWslugPslugSourcesRouteWithChildren
  '/w/$wslug/projects/new': typeof WWslugProjectsNewRoute
  '/w/$wslug/$pslug/': typeof WWslugPslugIndexRoute
  '/w/$wslug/$pslug/dashboards/$dslug': typeof WWslugPslugDashboardsDslugRoute
  '/w/$wslug/$pslug/dashboards/new': typeof WWslugPslugDashboardsNewRoute
  '/w/$wslug/$pslug/sources/new': typeof WWslugPslugSourcesNewRoute
  '/w/$wslug/$pslug/sources/': typeof WWslugPslugSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/new'
    | '/docs/$topic'
    | '/w/$wslug'
    | '/docs/'
    | '/w/$wslug/$pslug'
    | '/w/$wslug/events'
    | '/w/$wslug/members'
    | '/w/$wslug/settings'
    | '/w/$wslug/sources'
    | '/w/$wslug/usage'
    | '/w/$wslug/'
    | '/w/$wslug/$pslug/settings'
    | '/w/$wslug/$pslug/sources'
    | '/w/$wslug/projects/new'
    | '/w/$wslug/$pslug/'
    | '/w/$wslug/$pslug/dashboards/$dslug'
    | '/w/$wslug/$pslug/dashboards/new'
    | '/w/$wslug/$pslug/sources/new'
    | '/w/$wslug/$pslug/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/docs/$topic'
    | '/docs'
    | '/w/$wslug/events'
    | '/w/$wslug/members'
    | '/w/$wslug/settings'
    | '/w/$wslug/sources'
    | '/w/$wslug/usage'
    | '/w/$wslug'
    | '/w/$wslug/$pslug/settings'
    | '/w/$wslug/projects/new'
    | '/w/$wslug/$pslug'
    | '/w/$wslug/$pslug/dashboards/$dslug'
    | '/w/$wslug/$pslug/dashboards/new'
    | '/w/$wslug/$pslug/sources/new'
    | '/w/$wslug/$pslug/sources'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/login'
    | '/new'
    | '/docs/$topic'
    | '/w/$wslug'
    | '/docs/'
    | '/w/$wslug/$pslug'
    | '/w/$wslug/events'
    | '/w/$wslug/members'
    | '/w/$wslug/settings'
    | '/w/$wslug/sources'
    | '/w/$wslug/usage'
    | '/w/$wslug/'
    | '/w/$wslug/$pslug/settings'
    | '/w/$wslug/$pslug/sources'
    | '/w/$wslug/projects/new'
    | '/w/$wslug/$pslug/'
    | '/w/$wslug/$pslug/dashboards/$dslug'
    | '/w/$wslug/$pslug/dashboards/new'
    | '/w/$wslug/$pslug/sources/new'
    | '/w/$wslug/$pslug/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  WWslugRoute: typeof WWslugRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$topic': {
      id: '/docs/$topic'
      path: '/$topic'
      fullPath: '/docs/$topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/w/$wslug': {
      id: '/w/$wslug'
      path: '/w/$wslug'
      fullPath: '/w/$wslug'
      preLoaderRoute: typeof WWslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$wslug/': {
      id: '/w/$wslug/'
      path: '/'
      fullPath: '/w/$wslug/'
      preLoaderRoute: typeof WWslugIndexRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/$pslug': {
      id: '/w/$wslug/$pslug'
      path: '/$pslug'
      fullPath: '/w/$wslug/$pslug'
      preLoaderRoute: typeof WWslugPslugRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/events': {
      id: '/w/$wslug/events'
      path: '/events'
      fullPath: '/w/$wslug/events'
      preLoaderRoute: typeof WWslugEventsRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/members': {
      id: '/w/$wslug/members'
      path: '/members'
      fullPath: '/w/$wslug/members'
      preLoaderRoute: typeof WWslugMembersRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/settings': {
      id: '/w/$wslug/settings'
      path: '/settings'
      fullPath: '/w/$wslug/settings'
      preLoaderRoute: typeof WWslugSettingsRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/sources': {
      id: '/w/$wslug/sources'
      path: '/sources'
      fullPath: '/w/$wslug/sources'
      preLoaderRoute: typeof WWslugSourcesRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/usage': {
      id: '/w/$wslug/usage'
      path: '/usage'
      fullPath: '/w/$wslug/usage'
      preLoaderRoute: typeof WWslugUsageRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/$pslug/': {
      id: '/w/$wslug/$pslug/'
      path: '/'
      fullPath: '/w/$wslug/$pslug/'
      preLoaderRoute: typeof WWslugPslugIndexRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/settings': {
      id: '/w/$wslug/$pslug/settings'
      path: '/settings'
      fullPath: '/w/$wslug/$pslug/settings'
      preLoaderRoute: typeof WWslugPslugSettingsRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/sources': {
      id: '/w/$wslug/$pslug/sources'
      path: '/sources'
      fullPath: '/w/$wslug/$pslug/sources'
      preLoaderRoute: typeof WWslugPslugSourcesRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/projects/new': {
      id: '/w/$wslug/projects/new'
      path: '/projects/new'
      fullPath: '/w/$wslug/projects/new'
      preLoaderRoute: typeof WWslugProjectsNewRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/$pslug/dashboards/$dslug': {
      id: '/w/$wslug/$pslug/dashboards/$dslug'
      path: '/dashboards/$dslug'
      fullPath: '/w/$wslug/$pslug/dashboards/$dslug'
      preLoaderRoute: typeof WWslugPslugDashboardsDslugRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/dashboards/new': {
      id: '/w/$wslug/$pslug/dashboards/new'
      path: '/dashboards/new'
      fullPath: '/w/$wslug/$pslug/dashboards/new'
      preLoaderRoute: typeof WWslugPslugDashboardsNewRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/sources/': {
      id: '/w/$wslug/$pslug/sources/'
      path: '/'
      fullPath: '/w/$wslug/$pslug/sources/'
      preLoaderRoute: typeof WWslugPslugSourcesIndexRouteImport
      parentRoute: typeof WWslugPslugSourcesRoute
    }
    '/w/$wslug/$pslug/sources/new': {
      id: '/w/$wslug/$pslug/sources/new'
      path: '/new'
      fullPath: '/w/$wslug/$pslug/sources/new'
      preLoaderRoute: typeof WWslugPslugSourcesNewRouteImport
      parentRoute: typeof WWslugPslugSourcesRoute
    }
  }
}

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface WWslugPslugSourcesRouteChildren {
  WWslugPslugSourcesNewRoute: typeof WWslugPslugSourcesNewRoute
  WWslugPslugSourcesIndexRoute: typeof WWslugPslugSourcesIndexRoute
}

const WWslugPslugSourcesRouteChildren: WWslugPslugSourcesRouteChildren = {
  WWslugPslugSourcesNewRoute: WWslugPslugSourcesNewRoute,
  WWslugPslugSourcesIndexRoute: WWslugPslugSourcesIndexRoute,
}

const WWslugPslugSourcesRouteWithChildren =
  WWslugPslugSourcesRoute._addFileChildren(WWslugPslugSourcesRouteChildren)

interface WWslugPslugRouteChildren {
  WWslugPslugSettingsRoute: typeof WWslugPslugSettingsRoute
  WWslugPslugSourcesRoute: typeof WWslugPslugSourcesRouteWithChildren
  WWslugPslugIndexRoute: typeof WWslugPslugIndexRoute
  WWslugPslugDashboardsDslugRoute: typeof WWslugPslugDashboardsDslugRoute
  WWslugPslugDashboardsNewRoute: typeof WWslugPslugDashboardsNewRoute
}

const WWslugPslugRouteChildren: WWslugPslugRouteChildren = {
  WWslugPslugSettingsRoute: WWslugPslugSettingsRoute,
  WWslugPslugSourcesRoute: WWslugPslugSourcesRouteWithChildren,
  WWslugPslugIndexRoute: WWslugPslugIndexRoute,
  WWslugPslugDashboardsDslugRoute: WWslugPslugDashboardsDslugRoute,
  WWslugPslugDashboardsNewRoute: WWslugPslugDashboardsNewRoute,
}

const WWslugPslugRouteWithChildren = WWslugPslugRoute._addFileChildren(
  WWslugPslugRouteChildren,
)

interface WWslugRouteChildren {
  WWslugPslugRoute: typeof WWslugPslugRouteWithChildren
  WWslugEventsRoute: typeof WWslugEventsRoute
  WWslugMembersRoute: typeof WWslugMembersRoute
  WWslugSettingsRoute: typeof WWslugSettingsRoute
  WWslugSourcesRoute: typeof WWslugSourcesRoute
  WWslugUsageRoute: typeof WWslugUsageRoute
  WWslugIndexRoute: typeof WWslugIndexRoute
  WWslugProjectsNewRoute: typeof WWslugProjectsNewRoute
}

const WWslugRouteChildren: WWslugRouteChildren = {
  WWslugPslugRoute: WWslugPslugRouteWithChildren,
  WWslugEventsRoute: WWslugEventsRoute,
  WWslugMembersRoute: WWslugMembersRoute,
  WWslugSettingsRoute: WWslugSettingsRoute,
  WWslugSourcesRoute: WWslugSourcesRoute,
  WWslugUsageRoute: WWslugUsageRoute,
  WWslugIndexRoute: WWslugIndexRoute,
  WWslugProjectsNewRoute: WWslugProjectsNewRoute,
}

const WWslugRouteWithChildren =
  WWslugRoute._addFileChildren(WWslugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  WWslugRoute: WWslugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
