/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDatabaseRouteImport } from './routes/admin.database'
import { Route as AdminPartitionsRouteImport } from './routes/admin.partitions'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsTopicRouteImport } from './routes/docs.$topic'
import { Route as WWslugRouteImport } from './routes/w.$wslug'
import { Route as WWslugIndexRouteImport } from './routes/w.$wslug.index'
import { Route as WWslugPslugRouteImport } from './routes/w.$wslug.$pslug'
import { Route as WWslugEventsRouteImport } from './routes/w.$wslug.events'
import { Route as WWslugMembersRouteImport } from './routes/w.$wslug.members'
import { Route as WWslugSettingsRouteImport } from './routes/w.$wslug.settings'
import { Route as WWslugSourcesRouteImport } from './routes/w.$wslug.sources'
import { Route as WWslugUsageRouteImport } from './routes/w.$wslug.usage'
import { Route as WWslugPslugIndexRouteImport } from './routes/w.$wslug.$pslug.index'
import { Route as WWslugPslugSettingsRouteImport } from './routes/w.$wslug.$pslug.settings'
import { Route as WWslugPslugSourcesRouteImport } from './routes/w.$wslug.$pslug.sources'
import { Route as WWslugEventsIndexRouteImport } from './routes/w.$wslug.events.index'
import { Route as WWslugEventsEidRouteImport } from './routes/w.$wslug.events.$eid'
import { Route as WWslugProjectsNewRouteImport } from './routes/w.$wslug.projects.new'
import { Route as WWslugSettingsIndexRouteImport } from './routes/w.$wslug.settings.index'
import { Route as WWslugSettingsBillingRouteImport } from './routes/w.$wslug.settings.billing'
import { Route as WWslugSettingsProjectsRouteImport } from './routes/w.$wslug.settings.projects'
import { Route as WWslugPslugDashboardsDslugRouteImport } from './routes/w.$wslug.$pslug.dashboards.$dslug'
import { Route as WWslugPslugDashboardsNewRouteImport } from './routes/w.$wslug.$pslug.dashboards.new'
import { Route as WWslugPslugSourcesIndexRouteImport } from './routes/w.$wslug.$pslug.sources.index'
import { Route as WWslugPslugSourcesSidRouteImport } from './routes/w.$wslug.$pslug.sources.$sid'
import { Route as WWslugPslugSourcesNewRouteImport } from './routes/w.$wslug.$pslug.sources.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabaseRoute = AdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartitionsRoute = AdminPartitionsRouteImport.update({
  id: '/partitions',
  path: '/partitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => DocsRoute,
} as any)
const WWslugRoute = WWslugRouteImport.update({
  id: '/w/$wslug',
  path: '/w/$wslug',
  getParentRoute: () => rootRouteImport,
} as any)
const WWslugIndexRoute = WWslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPslugRoute = WWslugPslugRouteImport.update({
  id: '/$pslug',
  path: '/$pslug',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugEventsRoute = WWslugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugMembersRoute = WWslugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugSettingsRoute = WWslugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugSourcesRoute = WWslugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugUsageRoute = WWslugUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPslugIndexRoute = WWslugPslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugPslugRoute,
} as any)
const WWslugPslugSettingsRoute = WWslugPslugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWslugPslugRoute,
} as any)
const WWslugPslugSourcesRoute = WWslugPslugSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WWslugPslugRoute,
} as any)
const WWslugEventsIndexRoute = WWslugEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugEventsRoute,
} as any)
const WWslugEventsEidRoute = WWslugEventsEidRouteImport.update({
  id: '/$eid',
  path: '/$eid',
  getParentRoute: () => WWslugEventsRoute,
} as any)
const WWslugProjectsNewRoute = WWslugProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugSettingsIndexRoute = WWslugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugSettingsRoute,
} as any)
const WWslugSettingsBillingRoute = WWslugSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => WWslugSettingsRoute,
} as any)
const WWslugSettingsProjectsRoute = WWslugSettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WWslugSettingsRoute,
} as any)
const WWslugPslugDashboardsDslugRoute =
  WWslugPslugDashboardsDslugRouteImport.update({
    id: '/dashboards/$dslug',
    path: '/dashboards/$dslug',
    getParentRoute: () => WWslugPslugRoute,
  } as any)
const WWslugPslugDashboardsNewRoute =
  WWslugPslugDashboardsNewRouteImport.update({
    id: '/dashboards/new',
    path: '/dashboards/new',
    getParentRoute: () => WWslugPslugRoute,
  } as any)
const WWslugPslugSourcesIndexRoute = WWslugPslugSourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugPslugSourcesRoute,
} as any)
const WWslugPslugSourcesSidRoute = WWslugPslugSourcesSidRouteImport.update({
  id: '/$sid',
  path: '/$sid',
  getParentRoute: () => WWslugPslugSourcesRoute,
} as any)
const WWslugPslugSourcesNewRoute = WWslugPslugSourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WWslugPslugSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/partitions': typeof AdminPartitionsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/w/$wslug': typeof WWslugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/w/$wslug/$pslug': typeof WWslugPslugRouteWithChildren
  '/w/$wslug/events': typeof WWslugEventsRouteWithChildren
  '/w/$wslug/members': typeof WWslugMembersRoute
  '/w/$wslug/settings': typeof WWslugSettingsRouteWithChildren
  '/w/$wslug/sources': typeof WWslugSourcesRoute
  '/w/$wslug/usage': typeof WWslugUsageRoute
  '/w/$wslug/': typeof WWslugIndexRoute
  '/w/$wslug/$pslug/settings': typeof WWslugPslugSettingsRoute
  '/w/$wslug/$pslug/sources': typeof WWslugPslugSourcesRouteWithChildren
  '/w/$wslug/events/$eid': typeof WWslugEventsEidRoute
  '/w/$wslug/projects/new': typeof WWslugProjectsNewRoute
  '/w/$wslug/settings/billing': typeof WWslugSettingsBillingRoute
  '/w/$wslug/settings/projects': typeof WWslugSettingsProjectsRoute
  '/w/$wslug/$pslug/': typeof WWslugPslugIndexRoute
  '/w/$wslug/events/': typeof WWslugEventsIndexRoute
  '/w/$wslug/settings/': typeof WWslugSettingsIndexRoute
  '/w/$wslug/$pslug/dashboards/$dslug': typeof WWslugPslugDashboardsDslugRoute
  '/w/$wslug/$pslug/dashboards/new': typeof WWslugPslugDashboardsNewRoute
  '/w/$wslug/$pslug/sources/$sid': typeof WWslugPslugSourcesSidRoute
  '/w/$wslug/$pslug/sources/new': typeof WWslugPslugSourcesNewRoute
  '/w/$wslug/$pslug/sources/': typeof WWslugPslugSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/partitions': typeof AdminPartitionsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/w/$wslug/members': typeof WWslugMembersRoute
  '/w/$wslug/sources': typeof WWslugSourcesRoute
  '/w/$wslug/usage': typeof WWslugUsageRoute
  '/w/$wslug': typeof WWslugIndexRoute
  '/w/$wslug/$pslug/settings': typeof WWslugPslugSettingsRoute
  '/w/$wslug/events/$eid': typeof WWslugEventsEidRoute
  '/w/$wslug/projects/new': typeof WWslugProjectsNewRoute
  '/w/$wslug/settings/billing': typeof WWslugSettingsBillingRoute
  '/w/$wslug/settings/projects': typeof WWslugSettingsProjectsRoute
  '/w/$wslug/$pslug': typeof WWslugPslugIndexRoute
  '/w/$wslug/events': typeof WWslugEventsIndexRoute
  '/w/$wslug/settings': typeof WWslugSettingsIndexRoute
  '/w/$wslug/$pslug/dashboards/$dslug': typeof WWslugPslugDashboardsDslugRoute
  '/w/$wslug/$pslug/dashboards/new': typeof WWslugPslugDashboardsNewRoute
  '/w/$wslug/$pslug/sources/$sid': typeof WWslugPslugSourcesSidRoute
  '/w/$wslug/$pslug/sources/new': typeof WWslugPslugSourcesNewRoute
  '/w/$wslug/$pslug/sources': typeof WWslugPslugSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/partitions': typeof AdminPartitionsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/w/$wslug': typeof WWslugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/w/$wslug/$pslug': typeof WWslugPslugRouteWithChildren
  '/w/$wslug/events': typeof WWslugEventsRouteWithChildren
  '/w/$wslug/members': typeof WWslugMembersRoute
  '/w/$wslug/settings': typeof WWslugSettingsRouteWithChildren
  '/w/$wslug/sources': typeof WWslugSourcesRoute
  '/w/$wslug/usage': typeof WWslugUsageRoute
  '/w/$wslug/': typeof WWslugIndexRoute
  '/w/$wslug/$pslug/settings': typeof WWslugPslugSettingsRoute
  '/w/$wslug/$pslug/sources': typeof WWslugPslugSourcesRouteWithChildren
  '/w/$wslug/events/$eid': typeof WWslugEventsEidRoute
  '/w/$wslug/projects/new': typeof WWslugProjectsNewRoute
  '/w/$wslug/settings/billing': typeof WWslugSettingsBillingRoute
  '/w/$wslug/settings/projects': typeof WWslugSettingsProjectsRoute
  '/w/$wslug/$pslug/': typeof WWslugPslugIndexRoute
  '/w/$wslug/events/': typeof WWslugEventsIndexRoute
  '/w/$wslug/settings/': typeof WWslugSettingsIndexRoute
  '/w/$wslug/$pslug/dashboards/$dslug': typeof WWslugPslugDashboardsDslugRoute
  '/w/$wslug/$pslug/dashboards/new': typeof WWslugPslugDashboardsNewRoute
  '/w/$wslug/$pslug/sources/$sid': typeof WWslugPslugSourcesSidRoute
  '/w/$wslug/$pslug/sources/new': typeof WWslugPslugSourcesNewRoute
  '/w/$wslug/$pslug/sources/': typeof WWslugPslugSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/docs'
    | '/login'
    | '/new'
    | '/admin/database'
    | '/admin/partitions'
    | '/admin/workspaces'
    | '/docs/$topic'
    | '/w/$wslug'
    | '/admin/'
    | '/docs/'
    | '/w/$wslug/$pslug'
    | '/w/$wslug/events'
    | '/w/$wslug/members'
    | '/w/$wslug/settings'
    | '/w/$wslug/sources'
    | '/w/$wslug/usage'
    | '/w/$wslug/'
    | '/w/$wslug/$pslug/settings'
    | '/w/$wslug/$pslug/sources'
    | '/w/$wslug/events/$eid'
    | '/w/$wslug/projects/new'
    | '/w/$wslug/settings/billing'
    | '/w/$wslug/settings/projects'
    | '/w/$wslug/$pslug/'
    | '/w/$wslug/events/'
    | '/w/$wslug/settings/'
    | '/w/$wslug/$pslug/dashboards/$dslug'
    | '/w/$wslug/$pslug/dashboards/new'
    | '/w/$wslug/$pslug/sources/$sid'
    | '/w/$wslug/$pslug/sources/new'
    | '/w/$wslug/$pslug/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/admin/database'
    | '/admin/partitions'
    | '/admin/workspaces'
    | '/docs/$topic'
    | '/admin'
    | '/docs'
    | '/w/$wslug/members'
    | '/w/$wslug/sources'
    | '/w/$wslug/usage'
    | '/w/$wslug'
    | '/w/$wslug/$pslug/settings'
    | '/w/$wslug/events/$eid'
    | '/w/$wslug/projects/new'
    | '/w/$wslug/settings/billing'
    | '/w/$wslug/settings/projects'
    | '/w/$wslug/$pslug'
    | '/w/$wslug/events'
    | '/w/$wslug/settings'
    | '/w/$wslug/$pslug/dashboards/$dslug'
    | '/w/$wslug/$pslug/dashboards/new'
    | '/w/$wslug/$pslug/sources/$sid'
    | '/w/$wslug/$pslug/sources/new'
    | '/w/$wslug/$pslug/sources'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/docs'
    | '/login'
    | '/new'
    | '/admin/database'
    | '/admin/partitions'
    | '/admin/workspaces'
    | '/docs/$topic'
    | '/w/$wslug'
    | '/admin/'
    | '/docs/'
    | '/w/$wslug/$pslug'
    | '/w/$wslug/events'
    | '/w/$wslug/members'
    | '/w/$wslug/settings'
    | '/w/$wslug/sources'
    | '/w/$wslug/usage'
    | '/w/$wslug/'
    | '/w/$wslug/$pslug/settings'
    | '/w/$wslug/$pslug/sources'
    | '/w/$wslug/events/$eid'
    | '/w/$wslug/projects/new'
    | '/w/$wslug/settings/billing'
    | '/w/$wslug/settings/projects'
    | '/w/$wslug/$pslug/'
    | '/w/$wslug/events/'
    | '/w/$wslug/settings/'
    | '/w/$wslug/$pslug/dashboards/$dslug'
    | '/w/$wslug/$pslug/dashboards/new'
    | '/w/$wslug/$pslug/sources/$sid'
    | '/w/$wslug/$pslug/sources/new'
    | '/w/$wslug/$pslug/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  WWslugRoute: typeof WWslugRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/database': {
      id: '/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminDatabaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partitions': {
      id: '/admin/partitions'
      path: '/partitions'
      fullPath: '/admin/partitions'
      preLoaderRoute: typeof AdminPartitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$topic': {
      id: '/docs/$topic'
      path: '/$topic'
      fullPath: '/docs/$topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/w/$wslug': {
      id: '/w/$wslug'
      path: '/w/$wslug'
      fullPath: '/w/$wslug'
      preLoaderRoute: typeof WWslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$wslug/': {
      id: '/w/$wslug/'
      path: '/'
      fullPath: '/w/$wslug/'
      preLoaderRoute: typeof WWslugIndexRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/$pslug': {
      id: '/w/$wslug/$pslug'
      path: '/$pslug'
      fullPath: '/w/$wslug/$pslug'
      preLoaderRoute: typeof WWslugPslugRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/events': {
      id: '/w/$wslug/events'
      path: '/events'
      fullPath: '/w/$wslug/events'
      preLoaderRoute: typeof WWslugEventsRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/members': {
      id: '/w/$wslug/members'
      path: '/members'
      fullPath: '/w/$wslug/members'
      preLoaderRoute: typeof WWslugMembersRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/settings': {
      id: '/w/$wslug/settings'
      path: '/settings'
      fullPath: '/w/$wslug/settings'
      preLoaderRoute: typeof WWslugSettingsRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/sources': {
      id: '/w/$wslug/sources'
      path: '/sources'
      fullPath: '/w/$wslug/sources'
      preLoaderRoute: typeof WWslugSourcesRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/usage': {
      id: '/w/$wslug/usage'
      path: '/usage'
      fullPath: '/w/$wslug/usage'
      preLoaderRoute: typeof WWslugUsageRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/$pslug/': {
      id: '/w/$wslug/$pslug/'
      path: '/'
      fullPath: '/w/$wslug/$pslug/'
      preLoaderRoute: typeof WWslugPslugIndexRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/settings': {
      id: '/w/$wslug/$pslug/settings'
      path: '/settings'
      fullPath: '/w/$wslug/$pslug/settings'
      preLoaderRoute: typeof WWslugPslugSettingsRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/sources': {
      id: '/w/$wslug/$pslug/sources'
      path: '/sources'
      fullPath: '/w/$wslug/$pslug/sources'
      preLoaderRoute: typeof WWslugPslugSourcesRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/events/': {
      id: '/w/$wslug/events/'
      path: '/'
      fullPath: '/w/$wslug/events/'
      preLoaderRoute: typeof WWslugEventsIndexRouteImport
      parentRoute: typeof WWslugEventsRoute
    }
    '/w/$wslug/events/$eid': {
      id: '/w/$wslug/events/$eid'
      path: '/$eid'
      fullPath: '/w/$wslug/events/$eid'
      preLoaderRoute: typeof WWslugEventsEidRouteImport
      parentRoute: typeof WWslugEventsRoute
    }
    '/w/$wslug/projects/new': {
      id: '/w/$wslug/projects/new'
      path: '/projects/new'
      fullPath: '/w/$wslug/projects/new'
      preLoaderRoute: typeof WWslugProjectsNewRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/settings/': {
      id: '/w/$wslug/settings/'
      path: '/'
      fullPath: '/w/$wslug/settings/'
      preLoaderRoute: typeof WWslugSettingsIndexRouteImport
      parentRoute: typeof WWslugSettingsRoute
    }
    '/w/$wslug/settings/billing': {
      id: '/w/$wslug/settings/billing'
      path: '/billing'
      fullPath: '/w/$wslug/settings/billing'
      preLoaderRoute: typeof WWslugSettingsBillingRouteImport
      parentRoute: typeof WWslugSettingsRoute
    }
    '/w/$wslug/settings/projects': {
      id: '/w/$wslug/settings/projects'
      path: '/projects'
      fullPath: '/w/$wslug/settings/projects'
      preLoaderRoute: typeof WWslugSettingsProjectsRouteImport
      parentRoute: typeof WWslugSettingsRoute
    }
    '/w/$wslug/$pslug/dashboards/$dslug': {
      id: '/w/$wslug/$pslug/dashboards/$dslug'
      path: '/dashboards/$dslug'
      fullPath: '/w/$wslug/$pslug/dashboards/$dslug'
      preLoaderRoute: typeof WWslugPslugDashboardsDslugRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/dashboards/new': {
      id: '/w/$wslug/$pslug/dashboards/new'
      path: '/dashboards/new'
      fullPath: '/w/$wslug/$pslug/dashboards/new'
      preLoaderRoute: typeof WWslugPslugDashboardsNewRouteImport
      parentRoute: typeof WWslugPslugRoute
    }
    '/w/$wslug/$pslug/sources/': {
      id: '/w/$wslug/$pslug/sources/'
      path: '/'
      fullPath: '/w/$wslug/$pslug/sources/'
      preLoaderRoute: typeof WWslugPslugSourcesIndexRouteImport
      parentRoute: typeof WWslugPslugSourcesRoute
    }
    '/w/$wslug/$pslug/sources/$sid': {
      id: '/w/$wslug/$pslug/sources/$sid'
      path: '/$sid'
      fullPath: '/w/$wslug/$pslug/sources/$sid'
      preLoaderRoute: typeof WWslugPslugSourcesSidRouteImport
      parentRoute: typeof WWslugPslugSourcesRoute
    }
    '/w/$wslug/$pslug/sources/new': {
      id: '/w/$wslug/$pslug/sources/new'
      path: '/new'
      fullPath: '/w/$wslug/$pslug/sources/new'
      preLoaderRoute: typeof WWslugPslugSourcesNewRouteImport
      parentRoute: typeof WWslugPslugSourcesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDatabaseRoute: typeof AdminDatabaseRoute
  AdminPartitionsRoute: typeof AdminPartitionsRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDatabaseRoute: AdminDatabaseRoute,
  AdminPartitionsRoute: AdminPartitionsRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface WWslugPslugSourcesRouteChildren {
  WWslugPslugSourcesSidRoute: typeof WWslugPslugSourcesSidRoute
  WWslugPslugSourcesNewRoute: typeof WWslugPslugSourcesNewRoute
  WWslugPslugSourcesIndexRoute: typeof WWslugPslugSourcesIndexRoute
}

const WWslugPslugSourcesRouteChildren: WWslugPslugSourcesRouteChildren = {
  WWslugPslugSourcesSidRoute: WWslugPslugSourcesSidRoute,
  WWslugPslugSourcesNewRoute: WWslugPslugSourcesNewRoute,
  WWslugPslugSourcesIndexRoute: WWslugPslugSourcesIndexRoute,
}

const WWslugPslugSourcesRouteWithChildren =
  WWslugPslugSourcesRoute._addFileChildren(WWslugPslugSourcesRouteChildren)

interface WWslugPslugRouteChildren {
  WWslugPslugSettingsRoute: typeof WWslugPslugSettingsRoute
  WWslugPslugSourcesRoute: typeof WWslugPslugSourcesRouteWithChildren
  WWslugPslugIndexRoute: typeof WWslugPslugIndexRoute
  WWslugPslugDashboardsDslugRoute: typeof WWslugPslugDashboardsDslugRoute
  WWslugPslugDashboardsNewRoute: typeof WWslugPslugDashboardsNewRoute
}

const WWslugPslugRouteChildren: WWslugPslugRouteChildren = {
  WWslugPslugSettingsRoute: WWslugPslugSettingsRoute,
  WWslugPslugSourcesRoute: WWslugPslugSourcesRouteWithChildren,
  WWslugPslugIndexRoute: WWslugPslugIndexRoute,
  WWslugPslugDashboardsDslugRoute: WWslugPslugDashboardsDslugRoute,
  WWslugPslugDashboardsNewRoute: WWslugPslugDashboardsNewRoute,
}

const WWslugPslugRouteWithChildren = WWslugPslugRoute._addFileChildren(
  WWslugPslugRouteChildren,
)

interface WWslugEventsRouteChildren {
  WWslugEventsEidRoute: typeof WWslugEventsEidRoute
  WWslugEventsIndexRoute: typeof WWslugEventsIndexRoute
}

const WWslugEventsRouteChildren: WWslugEventsRouteChildren = {
  WWslugEventsEidRoute: WWslugEventsEidRoute,
  WWslugEventsIndexRoute: WWslugEventsIndexRoute,
}

const WWslugEventsRouteWithChildren = WWslugEventsRoute._addFileChildren(
  WWslugEventsRouteChildren,
)

interface WWslugSettingsRouteChildren {
  WWslugSettingsBillingRoute: typeof WWslugSettingsBillingRoute
  WWslugSettingsProjectsRoute: typeof WWslugSettingsProjectsRoute
  WWslugSettingsIndexRoute: typeof WWslugSettingsIndexRoute
}

const WWslugSettingsRouteChildren: WWslugSettingsRouteChildren = {
  WWslugSettingsBillingRoute: WWslugSettingsBillingRoute,
  WWslugSettingsProjectsRoute: WWslugSettingsProjectsRoute,
  WWslugSettingsIndexRoute: WWslugSettingsIndexRoute,
}

const WWslugSettingsRouteWithChildren = WWslugSettingsRoute._addFileChildren(
  WWslugSettingsRouteChildren,
)

interface WWslugRouteChildren {
  WWslugPslugRoute: typeof WWslugPslugRouteWithChildren
  WWslugEventsRoute: typeof WWslugEventsRouteWithChildren
  WWslugMembersRoute: typeof WWslugMembersRoute
  WWslugSettingsRoute: typeof WWslugSettingsRouteWithChildren
  WWslugSourcesRoute: typeof WWslugSourcesRoute
  WWslugUsageRoute: typeof WWslugUsageRoute
  WWslugIndexRoute: typeof WWslugIndexRoute
  WWslugProjectsNewRoute: typeof WWslugProjectsNewRoute
}

const WWslugRouteChildren: WWslugRouteChildren = {
  WWslugPslugRoute: WWslugPslugRouteWithChildren,
  WWslugEventsRoute: WWslugEventsRouteWithChildren,
  WWslugMembersRoute: WWslugMembersRoute,
  WWslugSettingsRoute: WWslugSettingsRouteWithChildren,
  WWslugSourcesRoute: WWslugSourcesRoute,
  WWslugUsageRoute: WWslugUsageRoute,
  WWslugIndexRoute: WWslugIndexRoute,
  WWslugProjectsNewRoute: WWslugProjectsNewRoute,
}

const WWslugRouteWithChildren =
  WWslugRoute._addFileChildren(WWslugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  WWslugRoute: WWslugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
